class Job_Form_Locators():
    # Global Add and Add Job ID's
    global_add_id = "//*[@class='nav-head']/mat-toolbar-row/div/div[2]/a[1]/a/i"
    add_job_button_id = "//*[@class='cdk-overlay-pane']/div/div/li[1]"
    company_name_textbox_id = "#Company\ Name"
    first_name_textbox_id = "#First\ Name"
    last_name_textbox_id = "#Last\ Name"
    additional_ref_textbox_id = "//*[text()='Additional Ref']/following::input[1]"
    save_job_button_id = "/html/body/app-root/main/section/app-job/div[11]/div/div[1]/div[2]/div[2]/button[1]"

    # Add Job Item ID's
    add_product_button_id = "//*[@id='dropdownMenuLink']"
    add_product_search_id = "//*[@id='selectProductcustom']"
    add_product_id = "(//*[text()='Roller'])[1]"
    room_id = "//*[text()='Room']/following::input[1]"
    blind_recess_id = "//*[text()='Blind or Recess']/following::input[1]"
    blind_option_id = "//*[text()='Blind']"
    width_id = "(//*[text()='Width'])[2]/following::input[1]"
    drop_id = "(//*[text()='Drop'])[2]/following::input[1]"
    product_type_id = "(//*[text()='Product Type'])[2]/following::select[1]"
    fabric_field_id = "(//*[text()='Fabric'])[2]/following::input[1]"
    fabric_id = "//*[contains(text(), 'Kaila')]"
    color_field_id = "//*[text()='Color']/following::input[1]"
    color_id = "//*[text()='Smoke']"
    job_item_save_button_id = "//*[@id=\"sampleModal1\"]/div/div/div[2]/div/div[2]/div[2]/button[1]"

    # Add Appointment ID's
    appointment_tab_id = "//*[@id='datessection']/mat-tab-header/div[2]/div/div/div[2]"
    add_appointment_id = "//*[@id='datessection']/div/mat-tab-body[2]/div/div/div/button"
    allday_id = "//*[@id='formID2']/div/div[2]/div[1]/div/div/label/div/label/span"
    appointment_type_id = "//*[text()='Appointment type ']/following::mat-select[1]"
    appointment_type_name_id = "//*[text()='Measurer']"
    staff_id = "//*[@id='employee']/div/div[1]/span"
    staff_name_id = "//*[@id='employee']/div/div[2]/ul[1]/li[1]/div"
    travel_time_id = "//*[@id='formID2']/div/div[5]/div/div[1]/div/div[1]"
    appointment_status_id = "//*[text()='Appointment Status ']/following::div[1]"
    appointment_status_name_id = "//*[text()=' Confirmed ']"
    appointment_description_id = "//*[@id='jobDescription']"
    appointment_save_button_id = "//*[@id='schedule_dialog_wrapper']/div[3]/button[2]"

    # Add Task ID's
    task_tab_id = "//*[@id='datessection']/mat-tab-header/div[2]/div/div/div[3]"
    add_task_id = "//*[@id='datessection']/div/mat-tab-body[3]/div/div/div/button"
    task_time_id = "(//*[text()='Add Task'])[2]/following::input[2]"
    repeat_toggle_id = "(//*[@id='addtaskbody']/div[1]/div/div[4]/div[2]/div/div/label/div)[2]"
    repeat_option_id = "//*[@id='RecurrenceEditor']/ejs-recurrenceeditor/div/div[1]/div"
    repeat_every_id = "//*[@id='RecurrenceEditor']/ejs-recurrenceeditor/div/div[2]/table/tbody/tr/td[1]/div/input[1]"
    repeat_end_id = "//*[@id='RecurrenceEditor']/ejs-recurrenceeditor/div/div[5]/div[2]/span"
    repeat_save_id = "//*[@id='RecurrenceEditor']/div/button[1]"
    task_description_id = "(//*[@id='taskdescription'])[2]"
    task_save_button_id = "(//*[@id='addtaskform']/div[4]/input)[2]"

    # Job Copy/Edit/Delete/Status ID's
    job_item_3dot_id = "//*[@id='jobproduct_grid']/div/div[2]/div[2]/div[3]/div[3]/div[1]/div[1]/app-moreoptionsrender/div/button/i"
    job_item_copy_id = "//*[@id='jobproduct_grid']/div/div[2]/div[2]/div[3]/div[3]/div[1]/div[1]/app-moreoptionsrender/div/div/a[1]"
    job_item_cost_price_id = "(//*[text()='Cost Price'])[2]/following::div[2]"
    job_item_cost_price_textbox_id = "(//*[text()='Cost Price'])[2]/following::input[2]"
    job_item_override_id = "//*[@id='pricecalc']"
    job_item_override_textbox_id = "//*[@id='collapseTwo']/div/form/div/div[5]/input"
    job_item_save_button_id = "//*[@id='sampleModal1']/div/div/div[2]/div/div[2]/div[2]/button[1]"
    job_item_All_select_id = "//*[@id='jobproduct_grid']/div/div[2]/div[2]/div[1]/div[1]/div[1]/div/div[2]/div[2]"
    job_from_3dot_options_id = "/html/body/app-root/main/section/app-job/div[11]/div/div[1]/div[2]/div[1]/div[1]/div[2]/div/div[2]/div/button"
    Job_from_3dot_copy_id = "/html/body/app-root/main/section/app-job/div[11]/div/div[1]/div[2]/div[1]/div[1]/div[2]/div/div[2]/div/div/button[5]"
    Job_from_3dot_paste_id = "/html/body/app-root/main/section/app-job/div[11]/div/div[1]/div[2]/div[1]/div[1]/div[2]/div/div[2]/div/div/button[6]"
    job_item_delete_id = "//*[@id='jobproduct_grid']/div/div[2]/div[2]/div[3]/div[3]/div[1]/div[1]/app-moreoptionsrender/div/div/a[3]"
    job_item_delete_ok_id = "//*[@id='deletecomomnotfication']/div/div/div/div/div/button[1]"
    job_status_dropdown_id = "(//*[text()='Job Status'])[3]/following::select[1]"
    order_status_dropdown_id = "(//*[text()='Order Status'])[3]/following::select[1]"

    # Add Payment ID's
    payment_tab_id = "//*[@id='pricedet']/mat-tab-header/div[2]/div/div/div[2]"
    add_payment_id = "//*[@id='pricedet']/div/mat-tab-body[2]/div/div/div/button"
    payment_amount_textbox_id = "//*[text()=' Amount ']/following::input[1]"
    payment_method_dropdown_id = "//*[text()=' Payment Method']/following::select[1]"
    payment_type_dropdown_id = "//*[text()=' Payment Type']/following::select[1]"
    payment_description_text_id = "//*[text()=' Notes']/following::textarea[1]"
    payment_save_button_id = "//*[@id='addpaymentModal']/div/div/form/div[3]/button[1]"

    # CheckList
    checklist_tab_id = "//*[@id='pricedet']/mat-tab-header/div[2]/div/div/div[3]"
    checklist_01_id = "//*[@id='pricedet']/div/mat-tab-body[3]/div/div[1]/div[1]/div[1]/input"
    checklist_02_id = "//*[@id='pricedet']/div/mat-tab-body[3]/div/div[1]/div[2]/div[1]/input"

    # Add Notes
    notes_tab_id = "//*[@id='notesshowmore']/mat-tab-header/div[2]/div/div/div[2]"
    add_notes_id = "//*[@id='notesshowmore']/div/mat-tab-body[2]/div/div/div/div/button"
    notes_type_dropdown_id = "//*[text()='Type ']/following::select[1]"
    notes_description_text_id = "(//*[text()=' Description']/following::textarea[1])[1]"
    notes_save_button_id = "//*[@id='addNotesModal']/div/div/form/div[3]/button[1]"

    # Alternative Delivery Address
    alter_deli_tab_id = "//*[@id='notesshowmore']/mat-tab-header/div[2]/div/div/div[1]"
    alter_deli_show_more_but_id = "//*[@id='notesshowmore']/div/mat-tab-body[1]/div/div/div[2]/button"
    alter_deli_appointment_id = "//*[@id='alterForm']/div[2]/div/div/div[1]/div/div/div/label/span"
    alter_deli_appointment_field_id = "//*[@id='alterForm']/div[2]/div/div/div[1]/div/div/div/span/div"
    alter_deli_appointment_contact_id = "//*[@id='alterForm']/div[2]/div/div/div[1]/div/div/div/span/div/div/div/a"
    alter_deli_invoice_id = "//*[@id='alterForm']/div[2]/div/div/div[2]/div/div/div/label/span"
    alter_deli_invoice_field_id = "//*[@id='alterForm']/div[2]/div/div/div[2]/div/div/div/span/div"
    alter_deli_invoice_contact_id = "//*[@id='alterForm']/div[2]/div/div/div[2]/div/div/div/span/div/div/div/a"
    alter_deli_invoice_contact_2_id = "(//*[@id='alterForm']/div[2]/div/div/div[2]/div/div/div/span/div/div/div/a)[2]"
    alter_deli_add_new_contact_id = "//*[@id='alterForm']/div[2]/div/div/div[2]/div/div/div/span/div/div/a"
    alter_deli_new_firstname_text_id = "(//*[text()='First Name'])[4]/following::input[1]"
    alter_deli_new_lastname_text_id = "(//*[text()='Last Name'])[2]/following::input[1]"
    alter_deli_new_contact_save_button_id = "//*[@id='custform']/div[2]/button[1]"
    alter_deli_save_button_id = "//*[@id='alterForm']/div[3]/button[1]"
