import time

import pyautogui
from selenium.webdriver import ActionChains
from selenium.webdriver.common.by import By
from selenium.webdriver.support.select import Select
from Locators.Contact_Module import Contact_Locators


class PaymentInfoTab():
    def __init__(self, driver):
        self.driver = driver

    def payment_info_tab(self):
        time.sleep(6)
        self.driver.find_element(By.XPATH, Contact_Locators.payment_info_tab).click()
        time.sleep(4)
        self.driver.find_element(By.XPATH, Contact_Locators.awaiting_payment_radio_button).click()
        time.sleep(3)
        FilterDate = self.driver.find_element(By.XPATH, Contact_Locators.payment_filter_dropdown)
        select = Select(FilterDate)
        select.select_by_visible_text("Last 30 Days")
        time.sleep(3)
        self.driver.find_element(By.XPATH, Contact_Locators.awaiting_amount_field).click()
        self.driver.find_element(By.XPATH, Contact_Locators.awaiting_amount_input).send_keys("4.89")
        self.driver.find_element(By.XPATH, Contact_Locators.payment_method_dropdown).click()
        self.driver.find_element(By.XPATH, Contact_Locators.payment_type_dropdown).click()
        self.driver.find_element(By.XPATH, Contact_Locators.paid_date_field).click()
        self.driver.find_element(By.XPATH, Contact_Locators.job_status_value).click()
        time.sleep(5)
        self.driver.find_element(By.XPATH, Contact_Locators.paid_radio_button).click()
        time.sleep(5)
        self.driver.find_element(By.XPATH, Contact_Locators.bulk_payment_button).click()
        time.sleep(3)
        PayMethod = self.driver.find_element(By.XPATH, Contact_Locators.bulk_payment_method_dropdown)
        select1 = Select(PayMethod)
        select1.select_by_visible_text("Paypal")
        PayType = self.driver.find_element(By.XPATH, Contact_Locators.bulk_payment_type_dropdown)
        select2 = Select(PayType)
        select2.select_by_visible_text("Intermediate")
        JobStatusBulk = self.driver.find_element(By.XPATH, Contact_Locators.bulk_job_status_filter_dropdown)
        select3 = Select(JobStatusBulk)
        select3.select_by_visible_text("Invoiced")
        time.sleep(3)
        self.driver.find_element(By.XPATH, Contact_Locators.bulk_job_checkbox).click()
        self.driver.find_element(By.XPATH, Contact_Locators.bulk_amount).send_keys("15.78")
        self.driver.find_element(By.XPATH, Contact_Locators.bulk_save_button).click()
        time.sleep(5)
        action = ActionChains(self.driver)
        action.move_to_element(self.driver.find_element(By.XPATH, Contact_Locators.account_info_tab)).click().perform()
        time.sleep(4)
        self.driver.find_element(By.XPATH, Contact_Locators.add_credit_field).send_keys("420")
        time.sleep(1)
        self.driver.find_element(By.XPATH, Contact_Locators.add_credit_plus).click()
        time.sleep(3)
        action = ActionChains(self.driver)
        action.move_to_element(self.driver.find_element(By.XPATH, Contact_Locators.payment_info_sub_tab)).click().perform()
        time.sleep(1)
        self.driver.find_element(By.XPATH, Contact_Locators.awaiting_payment_radio_button).click()
        time.sleep(6)
        self.driver.find_element(By.XPATH, Contact_Locators.awaiting_amount_field).click()
        self.driver.find_element(By.XPATH, Contact_Locators.awaiting_amount_input).send_keys("5.89")
        self.driver.find_element(By.XPATH, Contact_Locators.payment_method_dropdown).click()
        self.driver.find_element(By.XPATH, Contact_Locators.payment_type_dropdown).click()
        self.driver.find_element(By.XPATH, Contact_Locators.payment_type_dropdown).click()
        pyautogui.press('down')
        pyautogui.press('down')
        pyautogui.press('down')
        pyautogui.press('down')
        pyautogui.press('enter')
        self.driver.find_element(By.XPATH, Contact_Locators.paid_date_field).click()
        self.driver.find_element(By.XPATH, Contact_Locators.job_status_value).click()
        time.sleep(6)
        self.driver.find_element(By.XPATH, Contact_Locators.paid_radio_button).click()
        time.sleep(5)
        self.driver.find_element(By.XPATH, Contact_Locators.bulk_payment_button).click()
        time.sleep(3)
        PayMethod = self.driver.find_element(By.XPATH, Contact_Locators.bulk_payment_method_dropdown)
        select11 = Select(PayMethod)
        select11.select_by_visible_text("Paypal")
        PayType = self.driver.find_element(By.XPATH, Contact_Locators.bulk_payment_type_dropdown)
        select22 = Select(PayType)
        select22.select_by_visible_text("Redeem Credit Note")
        JobStatusBulk = self.driver.find_element(By.XPATH, Contact_Locators.bulk_job_status_filter_dropdown)
        select33 = Select(JobStatusBulk)
        select33.select_by_visible_text("Invoiced")
        time.sleep(3)
        self.driver.find_element(By.XPATH, Contact_Locators.bulk_job_checkbox).click()
        self.driver.find_element(By.XPATH, Contact_Locators.bulk_amount).send_keys("15.78")
        self.driver.find_element(By.XPATH, Contact_Locators.bulk_save_button).click()
