import time

import pyautogui
from selenium.webdriver.common.by import By
from selenium.webdriver.support.select import Select
from Locators.Contact_Module import Contact_Locators


class ProductConfigTab():
    def __init__(self, driver):
        self.driver = driver

    def product_config_tab(self):
        # Product Config - Product Enable/Disable
        time.sleep(6)
        self.driver.find_element(By.XPATH, Contact_Locators.product_config_tab).click()
        time.sleep(4)
        self.driver.find_element(By.XPATH, Contact_Locators.product_enable_disable_tab).click()
        time.sleep(1)
        self.driver.find_element(By.XPATH, Contact_Locators.product_enable_all_desktop).click()
        time.sleep(4)
        self.driver.find_element(By.XPATH, Contact_Locators.product_enable_all_online).click()
        time.sleep(4)
        self.driver.find_element(By.XPATH, Contact_Locators.product_enable_desktop_option1).click()
        time.sleep(3)
        self.driver.find_element(By.XPATH, Contact_Locators.product_enable_online_option1).click()
        time.sleep(3)
        self.driver.find_element(By.XPATH, Contact_Locators.product_enable_desktop_option2).click()
        time.sleep(3)
        self.driver.find_element(By.XPATH, Contact_Locators.product_enable_online_option2).click()
        time.sleep(3)
        DesktopFilter1 = self.driver.find_element(By.XPATH, Contact_Locators.product_desktop_filter1)
        select = Select(DesktopFilter1)
        select.select_by_visible_text("Checked")
        OnlineFilter1 = self.driver.find_element(By.XPATH, Contact_Locators.product_online_filter1)
        select = Select(OnlineFilter1)
        select.select_by_visible_text("Unchecked")
        DesktopFilter2 = self.driver.find_element(By.XPATH, Contact_Locators.product_desktop_filter2)
        select = Select(DesktopFilter2)
        select.select_by_visible_text("Checked")
        OnlineFilter2 = self.driver.find_element(By.XPATH, Contact_Locators.product_online_filter2)
        select = Select(OnlineFilter2)
        select.select_by_visible_text("Unchecked")
        DesktopFilter1 = self.driver.find_element(By.XPATH, Contact_Locators.product_desktop_filter1)
        select = Select(DesktopFilter1)
        select.select_by_visible_text("Select")
        OnlineFilter1 = self.driver.find_element(By.XPATH, Contact_Locators.product_online_filter1)
        select = Select(OnlineFilter1)
        select.select_by_visible_text("Select")
        DesktopFilter2 = self.driver.find_element(By.XPATH, Contact_Locators.product_desktop_filter2)
        select = Select(DesktopFilter2)
        select.select_by_visible_text("Select")
        OnlineFilter2 = self.driver.find_element(By.XPATH, Contact_Locators.product_online_filter2)
        select = Select(OnlineFilter2)
        select.select_by_visible_text("Select")
        self.driver.find_element(By.XPATH, Contact_Locators.product_enable_disable_tab).click()
        time.sleep(2)

        # Product Config - Price Group / Materials Discount
        self.driver.find_element(By.XPATH, Contact_Locators.price_group_disc_tab).click()
        time.sleep(1)
        self.driver.find_element(By.XPATH, Contact_Locators.price_group_disc_add_button).click()
        time.sleep(2)
        self.driver.find_element(By.XPATH, Contact_Locators.price_group_disc_field).send_keys("11.23")
        self.driver.find_element(By.XPATH, Contact_Locators.price_group_disc_supplier_field).click()
        self.driver.find_element(By.XPATH, Contact_Locators.price_group_disc_supplier_option1).click()
        time.sleep(3)
        self.driver.find_element(By.XPATH, Contact_Locators.price_group_disc_product_field).click()
        self.driver.find_element(By.XPATH, Contact_Locators.price_group_disc_product_option).click()
        time.sleep(3)
        self.driver.find_element(By.XPATH, Contact_Locators.price_group_disc_material_field).click()
        self.driver.find_element(By.XPATH, Contact_Locators.price_group_disc_material_all_checkbox).click()
        pyautogui.press('tab')
        time.sleep(1)
        self.driver.find_element(By.XPATH, Contact_Locators.price_group_disc_save_button).click()
        time.sleep(4)
        self.driver.find_element(By.XPATH, Contact_Locators.price_group_disc_add_button).click()
        time.sleep(2)
        self.driver.find_element(By.XPATH, Contact_Locators.price_group_disc_field).send_keys("11.23")
        self.driver.find_element(By.XPATH, Contact_Locators.price_group_disc_supplier_field).click()
        self.driver.find_element(By.XPATH, Contact_Locators.price_group_disc_supplier_option2).click()
        time.sleep(3)
        self.driver.find_element(By.XPATH, Contact_Locators.price_group_disc_product_field).click()
        self.driver.find_element(By.XPATH, Contact_Locators.price_group_disc_product_option).click()
        time.sleep(3)
        self.driver.find_element(By.XPATH, Contact_Locators.price_group_disc_material_field).click()
        self.driver.find_element(By.XPATH, Contact_Locators.price_group_disc_material_all_checkbox).click()
        pyautogui.press('tab')
        time.sleep(1)
        self.driver.find_element(By.XPATH, Contact_Locators.price_group_disc_save_button).click()
        time.sleep(3)
        self.driver.find_element(By.XPATH, Contact_Locators.price_group_disc_row1_checkbox).click()
        self.driver.find_element(By.XPATH, Contact_Locators.price_group_disc_3dot).click()
        self.driver.find_element(By.XPATH, Contact_Locators.price_group_disc_3dot_delete).click()
        time.sleep(1)
        self.driver.find_element(By.XPATH, Contact_Locators.price_group_disc_3dot_delete_ok).click()
        time.sleep(4)
        self.driver.find_element(By.XPATH, Contact_Locators.price_group_disc_tab).click()
        time.sleep(3)

        # Product Config - Option Discount
        self.driver.find_element(By.XPATH, Contact_Locators.option_disc_tab).click()
        time.sleep(1)
        self.driver.find_element(By.XPATH, Contact_Locators.option_disc_add_button).click()
        time.sleep(3)
        self.driver.find_element(By.XPATH, Contact_Locators.option_disc_field).send_keys("16.54")
        self.driver.find_element(By.XPATH, Contact_Locators.option_disc_name_dropdown).click()
        self.driver.find_element(By.XPATH, Contact_Locators.option_disc_name_option1).click()
        time.sleep(2)
        self.driver.find_element(By.XPATH, Contact_Locators.option_disc_product_field).click()
        time.sleep(1)
        self.driver.find_element(By.XPATH, Contact_Locators.option_disc_product_all_checkbox).click()
        pyautogui.press('tab')
        time.sleep(1)
        self.driver.find_element(By.XPATH, Contact_Locators.option_disc_save_button).click()
        time.sleep(3)
        self.driver.find_element(By.XPATH, Contact_Locators.option_disc_add_button).click()
        time.sleep(3)
        self.driver.find_element(By.XPATH, Contact_Locators.option_disc_field).send_keys("26.54")
        self.driver.find_element(By.XPATH, Contact_Locators.option_disc_name_dropdown).click()
        self.driver.find_element(By.XPATH, Contact_Locators.option_disc_name_option2).click()
        time.sleep(2)
        self.driver.find_element(By.XPATH, Contact_Locators.option_disc_product_field).click()
        time.sleep(1)
        self.driver.find_element(By.XPATH, Contact_Locators.option_disc_product_all_checkbox).click()
        pyautogui.press('tab')
        time.sleep(1)
        self.driver.find_element(By.XPATH, Contact_Locators.option_disc_save_button).click()
        time.sleep(3)
        self.driver.find_element(By.XPATH, Contact_Locators.option_disc_row1_checkbox).click()
        self.driver.find_element(By.XPATH, Contact_Locators.option_disc_3dot).click()
        self.driver.find_element(By.XPATH, Contact_Locators.option_disc_3dot_delete).click()
        time.sleep(1)
        self.driver.find_element(By.XPATH, Contact_Locators.option_disc_3dot_delete_ok).click()
        time.sleep(4)

        # Product Config - Product Gross Profit
        self.driver.find_element(By.XPATH, Contact_Locators.gross_profit_tab).click()
        time.sleep(1)
        self.driver.find_element(By.XPATH, Contact_Locators.gross_profit_add_button).click()
        time.sleep(2)
        self.driver.find_element(By.XPATH, Contact_Locators.gross_profit_field).send_keys("8.78")
        self.driver.find_element(By.XPATH, Contact_Locators.gross_profit_product_dropdown).click()
        time.sleep(1)
        self.driver.find_element(By.XPATH, Contact_Locators.gross_profit_product_option1).click()
        time.sleep(2)
        self.driver.find_element(By.XPATH, Contact_Locators.gross_profit_price_group_dropdown).click()
        self.driver.find_element(By.XPATH, Contact_Locators.gross_profit_price_group_all_checkbox).click()
        pyautogui.press('tab')
        self.driver.find_element(By.XPATH, Contact_Locators.gross_profit_save_button).click()
        time.sleep(3)
        self.driver.find_element(By.XPATH, Contact_Locators.gross_profit_add_button).click()
        time.sleep(2)
        self.driver.find_element(By.XPATH, Contact_Locators.gross_profit_field).send_keys("9.29")
        self.driver.find_element(By.XPATH, Contact_Locators.gross_profit_product_dropdown).click()
        time.sleep(1)
        self.driver.find_element(By.XPATH, Contact_Locators.gross_profit_product_option2).click()
        time.sleep(2)
        self.driver.find_element(By.XPATH, Contact_Locators.gross_profit_price_group_dropdown).click()
        self.driver.find_element(By.XPATH, Contact_Locators.gross_profit_price_group_all_checkbox).click()
        pyautogui.press('tab')
        self.driver.find_element(By.XPATH, Contact_Locators.gross_profit_save_button).click()
        time.sleep(3)
        self.driver.find_element(By.XPATH, Contact_Locators.gross_profit_row1_checkbox).click()
        self.driver.find_element(By.XPATH, Contact_Locators.gross_profit_3dot).click()
        self.driver.find_element(By.XPATH, Contact_Locators.gross_profit_3dot_delete).click()
        time.sleep(1)
        self.driver.find_element(By.XPATH, Contact_Locators.gross_profit_3dot_delete_ok).click()
        self.driver.find_element(By.XPATH, Contact_Locators.gross_profit_tab).click()
