import time
from datetime import datetime

import pyautogui
from selenium.webdriver import ActionChains
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.select import Select
from selenium import webdriver
from selenium.webdriver.common.by import By
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.chrome.options import Options

chrome_options = Options()
chrome_options.add_experimental_option("debuggerAddress", "localhost:9222")
options = webdriver.ChromeOptions()
options.add_experimental_option("detach", True)
prefs = {"profile.default_content_setting_values.notifications": 2}
options.add_experimental_option("prefs", prefs)
driver = webdriver.Chrome(executable_path=ChromeDriverManager().install(), options=chrome_options)
driver.maximize_window()
driver.implicitly_wait(10)

# Login
# driver.get("https://curtainmatrix.co.uk/finaltesting")
# driver.find_element(By.XPATH, "//*[@id='companyname']").send_keys("KISHORESIVADB")
# driver.find_element(By.CSS_SELECTOR, "#username").send_keys("admin")
# driver.find_element(By.CSS_SELECTOR, "#password").send_keys("1103")
# driver.find_element(By.XPATH, "/html/body/app-root/main/section/lib-login/div/div/div/div/div[2]/div/form/div[4]/button[1]").click()
# time.sleep(5)

# # Add Contact
# driver.find_element(By.XPATH, "//*[@class='nav-head']/mat-toolbar-row/div/div[1]/div/a[6]").click()
# time.sleep(4)
# driver.find_element(By.XPATH, "//*[@class='header']/div[2]/div/div[4]/button").click()
# driver.find_element(By.XPATH, "//*[@class='header']/div[2]/div/div[4]/div/a[1]").click()
# time.sleep(2)
# driver.find_element(By.XPATH, "//*[@id='contacttypemodel']/div/div/form/div/div/div[2]/mat-form-field").click()
# driver.find_element(By.XPATH, "(//*[@id='contact_choose-panel']/div/mat-option)[4]").click()
# driver.find_element(By.XPATH, "//*[@id='contacttypemodel']/div/div/form/div[3]/button[1]").click()
# time.sleep(5)
# driver.find_element(By.XPATH, "//*[@placeholder='Role']").send_keys("Tester")
# driver.find_element(By.XPATH, "//*[@id='First Name']").send_keys("Peace")
# driver.find_element(By.XPATH, "//*[@id='Last Name']").send_keys("Art")
# driver.find_element(By.XPATH, "(//*[text()='Phone'])[4]/following::input[1]").send_keys("235689")
# # (//*[@id="custform"]/div[1]/div/div)[2]/div[1]/div[5]/div/div[2]
# driver.find_element(By.XPATH, "//*[@placeholder='Mobile']").send_keys("9876543210")
# driver.find_element(By.XPATH, "(//*[text()='Email'])[2]/following::input[1]").send_keys("kishoresiva95@gmail.com")
# driver.find_element(By.XPATH, "(//*[text()='Default Contact']/following::input[1])[1]").click()
# driver.find_element(By.XPATH, "(//*[text()='Account Ref'])[2]/following::input[1]").send_keys("ACC004")
# pyautogui.scroll(-1500)
# driver.find_element(By.XPATH, "//*[text()='Company Name ']/following::input[1]").send_keys("2One Piece")
# driver.find_element(By.XPATH, "(//*[text()='Source'])[2]/following::div[1]").click()
# driver.find_element(By.XPATH, "//*[@class='cdk-overlay-container']/div/div/div/div/div/mat-option[3]").click()
# AddressType = driver.find_element(By.XPATH, "//*[@id='custform']/div[1]/div/div[4]/div[2]/div[1]/div/div[2]/app-dynamic-field/select")
# select = Select(AddressType)
# select.select_by_visible_text("Invoice Address")
# driver.find_element(By.XPATH, "//*[@id='contact_zipcodepostcode']").send_keys("MK13")
# driver.find_element(By.XPATH, "//*[@id='contactDynamicform']/span/i").click()
# time.sleep(2)
# driver.find_element(By.XPATH, "//*[text()='Contact Info ']/following::textarea[1]").clear()
# driver.find_element(By.XPATH, "//*[text()='Contact Info ']/following::textarea[1]").send_keys("Temple Tower")
# driver.find_element(By.XPATH, "//*[text()='Contact Info ']/following::textarea[2]").clear()
# driver.find_element(By.XPATH, "//*[text()='Contact Info ']/following::textarea[2]").send_keys("Anna Salai")
# driver.find_element(By.XPATH, "(//*[text()='Town / City']/following::input[1])[2]").clear()
# driver.find_element(By.XPATH, "(//*[text()='Town / City']/following::input[1])[2]").send_keys("Chennai")
# Country = driver.find_element(By.XPATH, "(//*[@id='contactDynamicform']/select)[3]")
# select = Select(Country)
# select.select_by_visible_text("USA")
# time.sleep(2)
# driver.find_element(By.XPATH, "//*[@id='contactDynamicform']/div/mat-form-field/div/div[1]/div/mat-select/div/div/span").click()
# time.sleep(2)
# driver.find_element(By.XPATH, "//*[@class='cdk-overlay-container']/div/div/div/div/div/mat-option[42]").click()
# driver.find_element(By.XPATH, "(//*[@name='ismarketingemails'])[1]").click()
# driver.find_element(By.XPATH, "(//*[@name='isdocumentreceived'])[1]").click()
# action = ActionChains(driver)
# action.move_to_element(driver.find_element(By.XPATH, "//*[@id='yes1']/following::i")).perform()
# driver.find_element(By.XPATH, "//*[@id='dynamic0']").click()
# driver.find_element(By.XPATH, "//*[@id='dynamic1']").click()
# driver.find_element(By.XPATH, "//*[@id='dynamic2']").click()
# driver.find_element(By.XPATH, "//*[@id='dynamic3']").click()
# driver.find_element(By.XPATH, "//*[@id='dynamic4']").click()
# driver.find_element(By.XPATH, "//*[@id='dynamic5']").click()
# driver.find_element(By.XPATH, "(//*[@name='isonlineportal'])[1]").click()
# action2 = ActionChains(driver)
# action2.move_to_element(driver.find_element(By.XPATH, "//*[text()='Set Configure ']")).perform()
# driver.find_element(By.XPATH, "//*[@placeholder='Enter Your Name']").send_keys("KishoreSiva1")
# driver.find_element(By.XPATH, "//*[@placeholder='Enter Your Password']").send_keys("1103")
# driver.find_element(By.XPATH, "//*[@placeholder='Enter Your Confirm Password']").send_keys("1103")
# driver.find_element(By.XPATH, "//*[@id='custform']/div[2]/button[1]").click()

# Add Job from Contact
# driver.find_element(By.XPATH, "//*[@id='cont_contact']/div/div[2]/div[2]/div[3]/div[3]/div/div/div/span").click()
# driver.find_element(By.XPATH, "//*[@id='cont_contact']/div/div[2]/div[2]/div[3]/div[3]/div[1]/div[1]/div/span/app-contactlisticon/div/div/div/div/button[2]").click()
# time.sleep(7)
# driver.find_element(By.XPATH, "(//*[text()='Customer Ref'])[3]/following::input[1]").send_keys("Automation Customer")
# driver.find_element(By.XPATH, "//*[text()='Additional Ref']/following::input[1]").send_keys("Automation Testing")
# driver.find_element(By.XPATH, "//*[text()='Status Notes']/following::input[1]").send_keys("Automation")
# driver.find_element(By.XPATH,"/html/body/app-root/main/section/app-job/div[11]/div/div[1]/div[2]/div[2]/button[1]").click()

# Go to Contact and Fill Company Details
# driver.find_element(By.XPATH, "/html/body/app-root/main/section/app-job/div[11]/div/div[1]/div[2]/div[1]/div[1]/div[2]/div/div[2]/div/button").click()
# driver.find_element(By.XPATH, "/html/body/app-root/main/section/app-job/div[11]/div/div[1]/div[2]/div[1]/div[1]/div[2]/div/div[2]/div/div/button[2]").click()
# time.sleep(2)
# current_window_handle = driver.current_window_handle
# window_handles = driver.window_handles
# next_window_handle = window_handles[(window_handles.index(current_window_handle) + 1) % len(window_handles)]
# driver.switch_to.window(next_window_handle)
# time.sleep(6)
# driver.find_element(By.XPATH, "(//*[@class='mat-tab-labels'])[2]/div[1]").click()
# driver.find_element(By.XPATH, "//*[@id='customform']/div[1]/div[1]/div/div[3]/div/div/div/div/div[2]/div/div[2]/app-dynamic-field/input").send_keys("ACC005")
# driver.find_element(By.XPATH, "//*[text()='Source']/following::mat-select[1]/div/div/span").click()
# driver.find_element(By.XPATH, "//*[@aria-label='dropdown search']").send_keys("FB")
# driver.find_element(By.XPATH, "//*[@class='cdk-overlay-pane']/div/div/div/mat-option[3]").click()
# driver.find_element(By.XPATH, "//*[@id='customform']/div[1]/div[1]/div/div[3]/div/div/div/div/div[5]/div/div[2]/app-dynamic-field/input").send_keys("234589")
# driver.find_element(By.XPATH, "//*[@id='customform']/div[1]/div[1]/div/div[3]/div/div/div/div/div[6]/div/div[2]/app-dynamic-field/input").send_keys("kishoresiva@gmail.com")
# driver.find_element(By.XPATH, "//*[@id='customform']/div[1]/div[1]/div/div[3]/div/div/div/div/div[7]/div/div[2]/app-dynamic-field/input").send_keys("www.kishoresiva.com")
# driver.find_element(By.XPATH, "//*[@id='customform']/div[1]/div[1]/div/div[3]/div/div/div/div/div[8]/div/div[2]/app-dynamic-field/input").send_keys("785612")
# driver.find_element(By.XPATH, "//*[@id='customform']/div[2]/button[1]").click()

# Pricing
# driver.find_element(By.XPATH, "(//*[@class='mat-tab-labels'])[2]/div[3]").click()
# time.sleep(4)
# driver.find_element(By.XPATH, "//*[text()='Customer-Specific VAT Rate']/following::input[1]").send_keys("45.56")
# pyautogui.press('tab')
# time.sleep(3)
# driver.find_element(By.XPATH, "//*[text()='VAT Registration Number']/following::input[1]").send_keys("ADTEX789456")
# pyautogui.press('tab')
# time.sleep(3)
# driver.find_element(By.XPATH, "//*[text()='Customer Surcharge(%)']/following::input[1]").send_keys("7.56")
# pyautogui.press('tab')
# time.sleep(3)
# driver.find_element(By.XPATH, "//*[text()='Default Delivery Cost']/following::input[1]").send_keys("14.23")
# pyautogui.press('tab')
# time.sleep(5)
# driver.find_element(By.XPATH, "//*[text()='Default Appointment Type']/following::mat-form-field[1]/div/div[1]/div/mat-select/div").click()
# driver.find_element(By.XPATH, "//*[@class='cdk-overlay-container']/div/div/div/div/input").send_keys("Measurer")
# driver.find_element(By.XPATH, "//*[@class='cdk-overlay-container']/div/div/div/div/div/mat-option[2]").click()
# time.sleep(5)
# driver.find_element(By.XPATH, "(//*[@class='col-xl-8 col-lg-6 col-md-8']/following::mat-select[1]/div)[2]/div[1]").click()
# driver.find_element(By.XPATH, "//*[@class='cdk-overlay-container']/div/div/div/div/div/mat-option[2]").click()

# Payment
# driver.find_element(By.XPATH, "(//*[@class='mat-tab-labels'])[2]/div[4]").click()
# time.sleep(4)
# driver.find_element(By.XPATH, "(//*[@class='radiomark'])[1]").click()
# time.sleep(3)
# FilterDate = driver.find_element(By.XPATH, "(//*[@class='radiomark'])[2]/following::select[1]")
# select = Select(FilterDate)
# select.select_by_visible_text("Last 30 Days")
# time.sleep(3)
# driver.find_element(By.XPATH, "//*[@id='accountonfogrid']/div/div[2]/div[2]/div[3]/div[2]/div/div/div/div[8]").click()
# driver.find_element(By.XPATH, "//*[@id='accountonfogrid']/div/div[2]/div[2]/div[3]/div[2]/div/div/div/div[8]/editor-cell/input").send_keys("4.89")
# driver.find_element(By.XPATH, "//*[@id='accountonfogrid']/div/div[2]/div[2]/div[3]/div[2]/div/div/div/div[9]").click()
# driver.find_element(By.XPATH, "//*[@id='accountonfogrid']/div/div[2]/div[2]/div[3]/div[2]/div/div/div/div[10]").click()
# driver.find_element(By.XPATH, "(//*[@col-id='paiddate'])[2]").click()
# driver.find_element(By.XPATH, "//*[@id='accountonfogrid']/div/div[2]/div[2]/div[3]/div[2]/div/div/div/div[3]").click()
# time.sleep(5)
# driver.find_element(By.XPATH, "(//*[@class='radiomark'])[2]").click()
# time.sleep(5)
# driver.find_element(By.XPATH, "//*[text()='Bulk Payments']").click()
# time.sleep(3)
# PayMethod = driver.find_element(By.XPATH, "//*[@id='payment_method']")
# select1 = Select(PayMethod)
# select1.select_by_visible_text("Paypal")
# PayType = driver.find_element(By.XPATH, "//*[@name='paymenttype']")
# select2 = Select(PayType)
# select2.select_by_visible_text("Intermediate")
# JobStatusBulk = driver.find_element(By.XPATH, "//*[@name='jobStatus']")
# select3 = Select(JobStatusBulk)
# select3.select_by_visible_text("Invoiced")
# time.sleep(3)
# driver.find_element(By.XPATH, "//*[@id='BulkUpdateModal']/div/div/form/div[2]/div[3]/ag-grid-angular/div/div[2]/div[2]/div[1]/div[2]/div/div[1]/div[1]/div[2]/div[2]/input").click()
# driver.find_element(By.XPATH, "//*[@name='amount']").send_keys("15.78")
# driver.find_element(By.XPATH, "//*[@id='BulkUpdateModal']/div/div/form/div[3]/button[1]").click()
# time.sleep(4)
# action = ActionChains(driver)
# action.move_to_element(driver.find_element(By.XPATH, "(//*[@class='mat-tab-labels'])[3]/div[2]/div")).click().perform()
# time.sleep(1)
# driver.find_element(By.XPATH, "//*[text()='Add Credit']/following::input[1]").send_keys("420")
# driver.find_element(By.XPATH, "//*[text()='Add Credit']/following::button[1]").click()
# time.sleep(2)
# driver.find_element(By.XPATH, "(//*[@class='mat-tab-labels'])[3]/div[1]").click()
# time.sleep(1)
# driver.find_element(By.XPATH, "(//*[@class='radiomark'])[1]").click()
# time.sleep(3)
# driver.find_element(By.XPATH, "//*[@id='accountonfogrid']/div/div[2]/div[2]/div[3]/div[2]/div/div/div/div[8]").click()
# driver.find_element(By.XPATH, "//*[@id='accountonfogrid']/div/div[2]/div[2]/div[3]/div[2]/div/div/div/div[8]/editor-cell/input").send_keys("5.89")
# driver.find_element(By.XPATH, "//*[@id='accountonfogrid']/div/div[2]/div[2]/div[3]/div[2]/div/div/div/div[9]").click()
# driver.find_element(By.XPATH, "//*[@id='accountonfogrid']/div/div[2]/div[2]/div[3]/div[2]/div/div/div/div[10]").click()
# driver.find_element(By.XPATH, "//*[@id='accountonfogrid']/div/div[2]/div[2]/div[3]/div[2]/div/div/div/div[10]").click()
# pyautogui.press('down')
# pyautogui.press('down')
# pyautogui.press('down')
# pyautogui.press('down')
# pyautogui.press('enter')
# driver.find_element(By.XPATH, "(//*[@col-id='paiddate'])[2]").click()
# driver.find_element(By.XPATH, "//*[@id='accountonfogrid']/div/div[2]/div[2]/div[3]/div[2]/div/div/div/div[3]").click()
# time.sleep(6)
# driver.find_element(By.XPATH, "(//*[@class='radiomark'])[2]").click()
# time.sleep(5)
# driver.find_element(By.XPATH, "//*[text()='Bulk Payments']").click()
# time.sleep(3)
# PayMethod = driver.find_element(By.XPATH, "//*[@id='payment_method']")
# select11 = Select(PayMethod)
# select11.select_by_visible_text("Paypal")
# PayType = driver.find_element(By.XPATH, "//*[@name='paymenttype']")
# select22 = Select(PayType)
# select22.select_by_visible_text("Redeem Credit Note")
# JobStatusBulk = driver.find_element(By.XPATH, "//*[@name='jobStatus']")
# select33 = Select(JobStatusBulk)
# select33.select_by_visible_text("Invoiced")
# time.sleep(3)
# driver.find_element(By.XPATH, "//*[@id='BulkUpdateModal']/div/div/form/div[2]/div[3]/ag-grid-angular/div/div[2]/div[2]/div[1]/div[2]/div/div[1]/div[1]/div[2]/div[2]/input").click()
# driver.find_element(By.XPATH, "//*[@name='amount']").send_keys("15.78")
# driver.find_element(By.XPATH, "//*[@id='BulkUpdateModal']/div/div/form/div[3]/button[1]").click()

# Commission
# driver.find_element(By.XPATH, "(//*[@class='mat-tab-labels'])[2]/div[5]").click()
# time.sleep(5)
# driver.find_element(By.XPATH, "//*[@class='Newaddbtn']").click()
# time.sleep(1)
# driver.find_element(By.XPATH, "//*[@id='commission']").send_keys("45.89")
# driver.find_element(By.XPATH, "(//*[text()='Sales Consultant'])[2]/following::mat-form-field[1]/div").click()
# driver.find_element(By.XPATH, "//*[@class='cdk-overlay-container']/div/div/div/div/mat-option[3]").click()
# driver.find_element(By.XPATH, "(//*[text()='Product'])[2]/following::mat-form-field[1]/div").click()
# driver.find_element(By.XPATH, "//*[@id='selectProduct']/following::mat-option[2]").click()
# driver.find_element(By.XPATH, "//*[@id='selectProduct']/following::mat-option[3]").click()
# driver.find_element(By.XPATH, "//*[@id='selectProduct']/following::mat-option[4]").click()
# pyautogui.press('tab')
# driver.find_element(By.XPATH, "//*[@class='greenbtn ng-star-inserted Newsavebtn Newsavebtn_Onchange']").click()
# time.sleep(4)
# driver.find_element(By.XPATH, "//*[@class='Newaddbtn']").click()
# time.sleep(1)
# driver.find_element(By.XPATH, "//*[@id='commission']").send_keys("25.89")
# driver.find_element(By.XPATH, "(//*[text()='Sales Consultant'])[2]/following::mat-form-field[1]/div").click()
# driver.find_element(By.XPATH, "//*[@class='cdk-overlay-container']/div/div/div/div/mat-option[2]").click()
# driver.find_element(By.XPATH, "(//*[text()='Product'])[2]/following::mat-form-field[1]/div").click()
# driver.find_element(By.XPATH, "//*[@id='selectProduct']/following::mat-option[2]").click()
# driver.find_element(By.XPATH, "//*[@id='selectProduct']/following::mat-option[3]").click()
# pyautogui.press('tab')
# driver.find_element(By.XPATH, "//*[@class='greenbtn ng-star-inserted Newsavebtn Newsavebtn_Onchange']").click()
# time.sleep(3)
# driver.find_element(By.XPATH, "//*[@id='commision']/div/div[2]/div[2]/div[3]/div[2]/div/div/div/div/div[1]").click()
# driver.find_element(By.XPATH, "//*[@id='commision']/div/div[2]/div[2]/div[1]/div[2]/div/div[1]/div[5]/div[3]/span/i").click()
# time.sleep(1)
# driver.find_element(By.XPATH, "//*[@id='commision']/div/div[6]/div/div[2]/div/app-commissionheader/div/div[3]/span").click()
# time.sleep(1)
# driver.find_element(By.XPATH, "//*[@id='deletecomomnotfication']/div/div/div/div/div/button[1]").click()
# time.sleep(3)
# driver.find_element(By.XPATH, "//*[text()=' Send Emails to The Consultant When Placed Orders Through Trade Online Portal ']/span").click()

# Document
# driver.find_element(By.XPATH, "(//*[@class='mat-tab-labels'])[2]/div[8]").click()
# time.sleep(4)
# driver.find_element(By.XPATH, "//*[@class='Newaddbtn']").click()
# time.sleep(2)
# driver.find_element(By.XPATH, "//*[@name='text']").send_keys("Automation")
# driver.find_element(By.XPATH, "//*[@id='addnotesdocform']/div[2]/div/div[2]/div/div[2]/div/input").send_keys("C:/Users/Shift 1/Downloads/Automation.docx")
# driver.find_element(By.XPATH, "//*[@id='addnotesdocform']/div[3]/button[1]").click()
# time.sleep(4)
# driver.find_element(By.XPATH, "//*[@class='Newaddbtn']").click()
# time.sleep(2)
# driver.find_element(By.XPATH, "//*[@name='text']").send_keys("Automation")
# driver.find_element(By.XPATH, "//*[@id='addnotesdocform']/div[2]/div/div[2]/div/div[2]/div/input").send_keys("C:/Users/Shift 1/Downloads/Automation.docx")
# driver.find_element(By.XPATH, "//*[@id='addnotesdocform']/div[2]/div/div[3]/div/div[2]/mat-form-field/div/div[1]/div/mat-select/div/div[1]").click()
# driver.find_element(By.XPATH, "//*[text()=' No']").click()
# driver.find_element(By.XPATH, "//*[@id='addnotesdocform']/div[3]/button[1]").click()
# time.sleep(3)
# driver.find_element(By.XPATH, "//*[@id='note']/div/div[2]/div[2]/div[3]/div[2]/div/div/div[1]/div[2]/div/div/div").click()
# driver.find_element(By.XPATH, "//*[@id='note']/div/div[2]/div[2]/div[1]/div[2]/div/div[1]/div[10]/div[3]/span").click()
# time.sleep(1)
# driver.find_element(By.XPATH, "//*[@id='note']/div/div[6]/div/div[2]/div/app-noteheader/div/div[3]/span").click()
# time.sleep(1)
# driver.find_element(By.XPATH, "//*[@id='deletecomomnotfication']/div/div/div/div/div/button[1]").click()

# # Product Config - Product Enable/Disable
# driver.find_element(By.XPATH, "(//*[@class='mat-tab-labels'])[2]/div[9]").click()
# time.sleep(4)
# driver.find_element(By.XPATH, "//*[@id='headingOne']/h5/button").click()
# time.sleep(1)
# driver.find_element(By.XPATH, "(//*[@name='enabledesktop'])[1]").click()
# time.sleep(4)
# driver.find_element(By.XPATH, "(//*[@name='enabledesktop'])[2]").click()
# time.sleep(4)
# driver.find_element(By.XPATH, "//*[@id='product-enable-disble-col1']/div/div[2]/div[2]/div[3]/div[2]/div/div/div[1]/div[2]/app-productdesktopcheckbox/label/span").click()
# time.sleep(3)
# driver.find_element(By.XPATH, "//*[@id='product-enable-disble-col1']/div/div[2]/div[2]/div[3]/div[2]/div/div/div[4]/div[3]/app-productononlinecheckbox/label/span").click()
# time.sleep(3)
# driver.find_element(By.XPATH, "//*[@id='product-enable-disble-col2']/div/div[2]/div[2]/div[3]/div[2]/div/div/div[1]/div[2]/app-productdesktopcheckbox/label/span").click()
# time.sleep(3)
# driver.find_element(By.XPATH, "//*[@id='product-enable-disble-col2']/div/div[2]/div[2]/div[3]/div[2]/div/div/div[4]/div[3]/app-productononlinecheckbox/label/span").click()
# time.sleep(3)
# DesktopFilter1 = driver.find_element(By.XPATH, "(//*[@name='sellist1'])[1]")
# select = Select(DesktopFilter1)
# select.select_by_visible_text("Checked")
# OnlineFilter1 = driver.find_element(By.XPATH, "(//*[@name='sellist1'])[2]")
# select = Select(OnlineFilter1)
# select.select_by_visible_text("Unchecked")
# DesktopFilter2 = driver.find_element(By.XPATH, "(//*[@name='sellist1'])[3]")
# select = Select(DesktopFilter2)
# select.select_by_visible_text("Checked")
# OnlineFilter2 = driver.find_element(By.XPATH, "(//*[@name='sellist1'])[4]")
# select = Select(OnlineFilter2)
# select.select_by_visible_text("Unchecked")
# DesktopFilter1 = driver.find_element(By.XPATH, "(//*[@name='sellist1'])[1]")
# select = Select(DesktopFilter1)
# select.select_by_visible_text("Select")
# OnlineFilter1 = driver.find_element(By.XPATH, "(//*[@name='sellist1'])[2]")
# select = Select(OnlineFilter1)
# select.select_by_visible_text("Select")
# DesktopFilter2 = driver.find_element(By.XPATH, "(//*[@name='sellist1'])[3]")
# select = Select(DesktopFilter2)
# select.select_by_visible_text("Select")
# OnlineFilter2 = driver.find_element(By.XPATH, "(//*[@name='sellist1'])[4]")
# select = Select(OnlineFilter2)
# select.select_by_visible_text("Select")
# driver.find_element(By.XPATH, "//*[@id='headingOne']/h5/button").click()
# time.sleep(2)
#
# # Product Config - Price Group / Materials Discount
# driver.find_element(By.XPATH, "//*[@id='headingtwo']/h5/button[1]").click()
# time.sleep(1)
# driver.find_element(By.XPATH, "//*[@id='headingtwo']/h5/button[2]").click()
# time.sleep(1)
# driver.find_element(By.XPATH, "//*[@id='discount']").send_keys("11.23")
# driver.find_element(By.XPATH, "(//*[text()='Supplier'])[2]/following::mat-select[1]/div/div[1]").click()
# driver.find_element(By.XPATH, "//*[@class='cdk-overlay-container']/div/div/div/div/div/mat-option[2]").click()
# time.sleep(3)
# driver.find_element(By.XPATH, "//*[@id='pricetabledis']/div[2]/div/div/div/div[6]/mat-form-field/div/div/div/mat-select/div/div/span").click()
# driver.find_element(By.XPATH, "//*[@class='cdk-overlay-container']/div/div/div/div/div/mat-option[1]").click()
# time.sleep(3)
# driver.find_element(By.XPATH, "(//*[text()='Select Material Group'])[1]").click()
# driver.find_element(By.XPATH, "(//*[@name='selectall'])[1]").click()
# pyautogui.press('tab')
# time.sleep(1)
# driver.find_element(By.XPATH, "//*[@id='pricetabledis']/div[3]/button[1]").click()
# time.sleep(4)
# driver.find_element(By.XPATH, "//*[@id='headingtwo']/h5/button[2]").click()
# time.sleep(1)
# driver.find_element(By.XPATH, "//*[@id='discount']").send_keys("11.23")
# driver.find_element(By.XPATH, "(//*[text()='Supplier'])[2]/following::mat-select[1]/div/div[1]").click()
# driver.find_element(By.XPATH, "//*[@class='cdk-overlay-container']/div/div/div/div/div/mat-option[1]").click()
# time.sleep(3)
# driver.find_element(By.XPATH, "//*[@id='pricetabledis']/div[2]/div/div/div/div[6]/mat-form-field/div/div/div/mat-select/div/div/span").click()
# driver.find_element(By.XPATH, "//*[@class='cdk-overlay-container']/div/div/div/div/div/mat-option[1]").click()
# time.sleep(3)
# driver.find_element(By.XPATH, "(//*[text()='Select Material Group'])[1]").click()
# driver.find_element(By.XPATH, "(//*[@name='selectall'])[1]").click()
# pyautogui.press('tab')
# time.sleep(1)
# driver.find_element(By.XPATH, "//*[@id='pricetabledis']/div[3]/button[1]").click()
# time.sleep(3)
# driver.find_element(By.XPATH, "//*[@id='contactdiscount']/div/div[2]/div[2]/div[3]/div[2]/div/div/div/div[1]/div/div/div/div[2]/input").click()
# driver.find_element(By.XPATH, "//*[@id='contactdiscount']/div/div[2]/div[2]/div[1]/div[2]/div/div[1]/div[7]/div[3]/span/i").click()
# driver.find_element(By.XPATH, "//*[@id='contactdiscount']/div/div[6]/div/div[2]/div/app-discountheader/div/div[3]/span").click()
# time.sleep(1)
# driver.find_element(By.XPATH, "//*[@id='deletecomomnotfication']/div/div/div/div/div/button[1]").click()
# time.sleep(4)
# driver.find_element(By.XPATH, "//*[@id='headingtwo']/h5/button[1]").click()
# time.sleep(3)
#
# # Product Config - Option Discount
# driver.find_element(By.XPATH, "//*[@id='headingthree']/h5/button").click()
# time.sleep(1)
# driver.find_element(By.XPATH, "//*[@id='headingthree']/h5/button[2]").click()
# time.sleep(3)
# driver.find_element(By.XPATH, "//*[@id='common_discount']").send_keys("16.54")
# driver.find_element(By.XPATH, "//*[@id='dropdownMenuButton']/div").click()
# driver.find_element(By.XPATH, "//*[@id='componentdiscount']/div/div[2]/div[2]/div[3]/div[2]/div/div/div[1]/div[1]").click()
# time.sleep(2)
# driver.find_element(By.XPATH, "(//*[text()='Products'])[2]/following::span[2]").click()
# time.sleep(1)
# driver.find_element(By.XPATH, "//*[text()=' All ']").click()
# pyautogui.press('tab')
# time.sleep(1)
# driver.find_element(By.XPATH, "//*[@id='adddiscountform']/div[3]/button[1]").click()
# time.sleep(3)
# driver.find_element(By.XPATH, "//*[@id='headingthree']/h5/button[2]").click()
# time.sleep(3)
# driver.find_element(By.XPATH, "//*[@id='common_discount']").send_keys("16.54")
# driver.find_element(By.XPATH, "//*[@id='dropdownMenuButton']/div").click()
# driver.find_element(By.XPATH, "//*[@id='componentdiscount']/div/div[2]/div[2]/div[3]/div[2]/div/div/div[2]/div[1]").click()
# time.sleep(2)
# driver.find_element(By.XPATH, "(//*[text()='Products'])[2]/following::span[2]").click()
# time.sleep(1)
# driver.find_element(By.XPATH, "//*[text()=' All ']").click()
# pyautogui.press('tab')
# time.sleep(1)
# driver.find_element(By.XPATH, "//*[@id='adddiscountform']/div[3]/button[1]").click()
# time.sleep(3)
# driver.find_element(By.XPATH, "//*[@id='componentdiscount']/div/div[2]/div[2]/div[3]/div[2]/div/div/div/div[2]/div/div/div").click()
# driver.find_element(By.XPATH, "//*[@id='componentdiscount']/div/div[2]/div[2]/div[1]/div[2]/div/div[1]/div[8]/div[3]/span").click()
# driver.find_element(By.XPATH, "//*[@id='componentdiscount']/div/div[6]/div/div[2]/div/app-discountmultidelete/div/div[3]/span").click()
# time.sleep(1)
# driver.find_element(By.XPATH, "//*[@id='deletecomomnotfication']/div/div/div/div/div/button[1]").click()
# time.sleep(4)
# #
# # # Product Config - Product Gross Profit
# driver.find_element(By.XPATH, "//*[@id='headingfour']/h5/button").click()
# time.sleep(1)
# driver.find_element(By.XPATH, "//*[@id='headingfour']/h5/button[2]").click()
# time.sleep(2)
# driver.find_element(By.XPATH, "(//*[text()='Gross Profit'])[2]/following::input").send_keys("8.78")
# driver.find_element(By.XPATH, "(//*[text()='Product'])[4]/following::span[2]").click()
# driver.find_element(By.XPATH, "//*[@class='cdk-overlay-pane']/div/div/div/mat-option[2]").click()
# time.sleep(2)
# driver.find_element(By.XPATH, "(//*[text()='Pricing Group'])[2]/following::span[2]").click()
# driver.find_element(By.XPATH, "//*[@class='cdk-overlay-pane']/div/div/div/div/mat-checkbox").click()
# pyautogui.press('tab')
# driver.find_element(By.XPATH, "//*[@id='grossprofitform']/div[3]/button[1]").click()
# time.sleep(3)
# driver.find_element(By.XPATH, "//*[@id='headingfour']/h5/button[2]").click()
# time.sleep(2)
# driver.find_element(By.XPATH, "(//*[text()='Gross Profit'])[2]/following::input").send_keys("9.29")
# driver.find_element(By.XPATH, "(//*[text()='Product'])[4]/following::span[2]").click()
# driver.find_element(By.XPATH, "//*[@class='cdk-overlay-pane']/div/div/div/mat-option[3]").click()
# time.sleep(2)
# driver.find_element(By.XPATH, "(//*[text()='Pricing Group'])[2]/following::span[2]").click()
# driver.find_element(By.XPATH, "//*[@class='cdk-overlay-pane']/div/div/div/div/mat-checkbox").click()
# pyautogui.press('tab')
# driver.find_element(By.XPATH, "//*[@id='grossprofitform']/div[3]/button[1]").click()
# time.sleep(3)
# driver.find_element(By.XPATH, "//*[@id='gross']/div/div[2]/div[2]/div[3]/div[2]/div/div/div[1]/div[2]/div/div/div").click()
# driver.find_element(By.XPATH, "//*[@id='gross']/div/div[2]/div[2]/div[1]/div[2]/div/div[1]/div[7]/div[3]/span/i").click()
# driver.find_element(By.XPATH, "//*[@id='gross']/div/div[6]/div/div[2]/div/lib-grossprofitheadercell/div/div[3]/span").click()
# time.sleep(1)
# driver.find_element(By.XPATH, "//*[@id='deletecomomnotfication']/div/div/div/div/div/button[1]").click()
# driver.find_element(By.XPATH, "//*[@id='headingfour']/h5/button").click()

# Online Portal
# driver.find_element(By.XPATH, "(//*[@class='mat-tab-labels'])[2]/div[10]").click()
# time.sleep(4)
# Alljobs = driver.find_element(By.XPATH, "//*[@id='alljobview']")
# select1 = Select(Alljobs)
# select1.select_by_visible_text("Default View")
# time.sleep(4)
# driver.find_element(By.XPATH, "//*[@id='discountorder']").clear()
# time.sleep(2)
# driver.find_element(By.XPATH, "//*[@id='discountorder']").send_keys("15")
# pyautogui.press('tab')
# time.sleep(3)
# Language = driver.find_element(By.XPATH, "//*[@id='orderlanguage']")
# select2 = Select(Language)
# select2.select_by_visible_text("English")
# time.sleep(3)
# Notification = driver.find_element(By.XPATH, "//*[@id='Notification']")
# select3 = Select(Notification)
# select3.select_by_visible_text("Acknowledge Template")

#  FTP
# driver.find_element(By.XPATH, "(//*[@class='mat-tab-labels'])[2]/div[11]").click()
# time.sleep(4)
# driver.find_element(By.XPATH, "//*[@class='Newaddbtn']").click()
# time.sleep(1)
# Format = driver.find_element(By.XPATH, "//*[@id='for_mat']")
# select1 = Select(Format)
# select1.select_by_visible_text("XML")
# Status = driver.find_element(By.XPATH, "//*[@id='status']")
# select2 = Select(Status)
# select2.select_by_visible_text("Invoice")
# driver.find_element(By.XPATH, "//*[@id='hostname']").send_keys("KishoreSiva")
# driver.find_element(By.XPATH, "//*[@id='username1']").send_keys("PeaceArt")
# driver.find_element(By.XPATH, "//*[@id='password1']").send_keys("1103")
# driver.find_element(By.XPATH, "//*[@id='path']").send_keys("Automation")
# driver.find_element(By.XPATH, "//*[@id='port']").send_keys("12.498.156")
# Protocol = driver.find_element(By.XPATH, "//*[@id='protocol']")
# select2 = Select(Protocol)
# select2.select_by_visible_text("FTP")
# driver.find_element(By.XPATH, "//*[@id='ftppopup']/div/div/form/div[3]/button[1]").click()
# time.sleep(5)
# driver.find_element(By.XPATH, "//*[@class='Newaddbtn']").click()
# time.sleep(1)
# Format = driver.find_element(By.XPATH, "//*[@id='for_mat']")
# select1 = Select(Format)
# select1.select_by_visible_text("CSV")
# Status = driver.find_element(By.XPATH, "//*[@id='status']")
# select2 = Select(Status)
# select2.select_by_visible_text("Delivery Manifest")
# driver.find_element(By.XPATH, "//*[@id='hostname']").send_keys("KishoreSiva1")
# driver.find_element(By.XPATH, "//*[@id='username1']").send_keys("PeaceArt1")
# driver.find_element(By.XPATH, "//*[@id='password1']").send_keys("1103")
# driver.find_element(By.XPATH, "//*[@id='path']").send_keys("Automation1")
# driver.find_element(By.XPATH, "//*[@id='port']").send_keys("12.498.156.2")
# Protocol = driver.find_element(By.XPATH, "//*[@id='protocol']")
# select2 = Select(Protocol)
# select2.select_by_visible_text("SFTP")
# driver.find_element(By.XPATH, "//*[@id='ftppopup']/div/div/form/div[3]/button[1]").click()
# time.sleep(4)
# action = ActionChains(driver)
# action.move_to_element(driver.find_element(By.XPATH, "//*[@id='ftpdetails']/div/div[2]/div[2]/div[3]/div[2]/div/div/div/div[10]/app-ftpdelete")).click().perform()
# time.sleep(1)
# driver.find_element(By.XPATH, "//*[@id='deletecomomnotfication']/div/div/div/div/div/button[1]").click()

# Add Task from 3dots
# driver.find_element(By.XPATH, "html/body/app-root/main/section/app-customer/div[1]/ul/li[1]/span").click()
# time.sleep(6)
# driver.find_element(By.XPATH, "//*[@id='cont_contact']/div/div[2]/div[2]/div[3]/div[3]/div[1]/div[1]/div/span/app-contactlisticon/div/div/div/button/i").click()
# driver.find_element(By.XPATH, "//*[@id='cont_contact']/div/div[2]/div[2]/div[3]/div[3]/div[1]/div[1]/div/span/app-contactlisticon/div/div/div/div/button[3]").click()
# time.sleep(3)
# driver.find_element(By.XPATH, "(//*[text()='Add Task'])[2]/following::input[2]").click()
# driver.find_element(By.XPATH, "(//*[text()='Add Task'])[2]/following::input[2]").send_keys("1245PM")
# driver.find_element(By.XPATH, "(//*[@id='addtaskbody']/div[1]/div/div[4]/div[2]/div/div/label/div)[2]").click()
# driver.find_element(By.XPATH, "//*[@id='RecurrenceEditor']/ejs-recurrenceeditor/div/div[1]/div").click()
# time.sleep(2)
# pyautogui.press('down')
# pyautogui.press('enter')
# driver.find_element(By.XPATH, "//*[@id='RecurrenceEditor']/ejs-recurrenceeditor/div/div[2]/table/tbody/tr/td[1]/div/input[1]").click()
# time.sleep(1)
# driver.find_element(By.XPATH, "//*[@id='RecurrenceEditor']/ejs-recurrenceeditor/div/div[2]/table/tbody/tr/td[1]/div/input[1]").send_keys("4")
# driver.find_element(By.XPATH, "//*[@id='RecurrenceEditor']/ejs-recurrenceeditor/div/div[5]/div[2]/span").click()
# pyautogui.press('down')
# pyautogui.press('enter')
# time.sleep(1)
# driver.find_element(By.XPATH, "//*[@id='RecurrenceEditor']/div/button[1]").click()
# time.sleep(3)
# driver.find_element(By.XPATH, "(//*[@id='taskdescription'])[2]").send_keys("Automation Test")
# driver.find_element(By.XPATH, "(//*[@id='addtaskform']/div[4]/input)[2]").click()
# time.sleep(5)

# Add Appointment from 3dots
# driver.find_element(By.XPATH, "//*[@id='cont_contact']/div/div[2]/div[2]/div[3]/div[3]/div[1]/div[1]/div/span/app-contactlisticon/div/div/div/button/i").click()
# driver.find_element(By.XPATH, "//*[@id='cont_contact']/div/div[2]/div[2]/div[3]/div[3]/div[1]/div[1]/div/span/app-contactlisticon/div/div/div/div/button[4]").click()
# time.sleep(8)
# driver.find_element(By.XPATH, "//*[@id='formID2']/div/div[2]/div[1]/div/div/label/div/label/span").click()
# driver.find_element(By.XPATH, "//*[@id='repeatflag']/div/div/label/div").click()
# time.sleep(2)
# action = ActionChains(driver)
# action.move_to_element(driver.find_element(By.XPATH, "//*[@id='scheduleEditForm']/div[1]/div/div[1]/div/div[1]/div/input")).click().perform()
# # driver.find_element(By.XPATH, "//*[@id='scheduleEditForm']/div[1]/div/div[1]/div/div[1]/div/input").click()
# time.sleep(1)
# pyautogui.press('down')
# pyautogui.press('enter')
# driver.find_element(By.XPATH, "//*[@id='scheduleEditForm']/div[1]/div/div[1]/div/div[2]/table/tbody/tr/td/div/input[1]").click()
# time.sleep(1)
# driver.find_element(By.XPATH, "//*[@id='scheduleEditForm']/div[1]/div/div[1]/div/div[2]/table/tbody/tr/td/div/input[1]").send_keys("4")
# driver.find_element(By.XPATH, "//*[@id='scheduleEditForm']/div[1]/div/div[2]/button[1]").click()
# time.sleep(2)
# driver.find_element(By.XPATH, "//*[text()='Appointment type ']/following::mat-select[1]").click()
# driver.find_element(By.XPATH, "//*[text()='Measurer']").click()
# driver.find_element(By.XPATH, "//*[@id='employee']/div/div[1]/span").click()
# time.sleep(4)
# driver.find_element(By.XPATH, "//*[@id='employee']/div/div[2]/ul[1]/li[1]/div").click()
# time.sleep(3)
# driver.find_element(By.XPATH, "//*[@id='formID2']/div/div[5]/div/div[1]/div/div[1]").click()
# driver.find_element(By.XPATH, "//*[text()='Appointment Status ']/following::div[1]").click()
# driver.find_element(By.XPATH, "//*[text()=' Confirmed ']").click()
# driver.find_element(By.XPATH, "//*[@id='jobDescription']").send_keys("Automation Test")
# driver.find_element(By.XPATH, "//*[@id='schedule_dialog_wrapper']/div[3]/button[2]").click()
# time.sleep(6)

# Add Task from Contact Tab
# driver.find_element(By.XPATH, "//*[@id='cont_contact']/div/div[2]/div[2]/div[3]/div[2]/div/div/div[1]/div[3]/div/span/span/a").click()
# time.sleep(9)
# driver.find_element(By.XPATH, "//*[@id='leadcustform']/div[2]/button[2]").click()
# time.sleep(10)
# action = ActionChains(driver)
# action.move_to_element(driver.find_element(By.XPATH, "//*[@id='myGridcontact']/div/div[2]/div[2]/div[3]/div[3]/div/div[3]")).click().perform()
# time.sleep(3)
# driver.find_element(By.XPATH, "(//*[text()='Add Task'])[2]/following::input[2]").click()
# driver.find_element(By.XPATH, "(//*[text()='Add Task'])[2]/following::input[2]").send_keys("1245PM")
# driver.find_element(By.XPATH, "(//*[@id='addtaskbody']/div[1]/div/div[4]/div[2]/div/div/label/div)[2]").click()
# driver.find_element(By.XPATH, "//*[@id='RecurrenceEditor']/ejs-recurrenceeditor/div/div[1]/div").click()
# time.sleep(2)
# pyautogui.press('down')
# pyautogui.press('enter')
# driver.find_element(By.XPATH, "//*[@id='RecurrenceEditor']/ejs-recurrenceeditor/div/div[2]/table/tbody/tr/td[1]/div/input[1]").click()
# time.sleep(1)
# driver.find_element(By.XPATH, "//*[@id='RecurrenceEditor']/ejs-recurrenceeditor/div/div[2]/table/tbody/tr/td[1]/div/input[1]").send_keys("4")
# driver.find_element(By.XPATH, "//*[@id='RecurrenceEditor']/ejs-recurrenceeditor/div/div[5]/div[2]/span").click()
# pyautogui.press('down')
# pyautogui.press('enter')
# time.sleep(1)
# driver.find_element(By.XPATH, "//*[@id='RecurrenceEditor']/div/button[1]").click()
# time.sleep(3)
# driver.find_element(By.XPATH, "(//*[@id='taskdescription'])[2]").send_keys("Automation Test")
# driver.find_element(By.XPATH, "(//*[@id='addtaskform']/div[4]/input)[2]").click()
# time.sleep(5)

# Add Appointment from Contact Tab
# action = ActionChains(driver)
# action.move_to_element(driver.find_element(By.XPATH, "//*[@id='myGridcontact']/div/div[2]/div[2]/div[3]/div[3]/div/div[2]")).click().perform()
# time.sleep(8)
# driver.find_element(By.XPATH, "//*[@id='formID2']/div/div[2]/div[1]/div/div/label/div/label/span").click()
# driver.find_element(By.XPATH, "//*[@id='repeatflag']/div/div/label/div").click()
# time.sleep(2)
# action = ActionChains(driver)
# action.move_to_element(driver.find_element(By.XPATH, "//*[@id='scheduleEditForm']/div[1]/div/div[1]/div/div[1]/div/input")).click().perform()
# time.sleep(1)
# pyautogui.press('down')
# pyautogui.press('enter')
# driver.find_element(By.XPATH, "//*[@id='scheduleEditForm']/div[1]/div/div[1]/div/div[2]/table/tbody/tr/td/div/input[1]").click()
# time.sleep(1)
# driver.find_element(By.XPATH, "//*[@id='scheduleEditForm']/div[1]/div/div[1]/div/div[2]/table/tbody/tr/td/div/input[1]").send_keys("4")
# driver.find_element(By.XPATH, "//*[@id='scheduleEditForm']/div[1]/div/div[2]/button[1]").click()
# time.sleep(2)
# driver.find_element(By.XPATH, "//*[text()='Appointment type ']/following::mat-select[1]").click()
# driver.find_element(By.XPATH, "//*[text()='Measurer']").click()
# driver.find_element(By.XPATH, "//*[@id='employee']/div/div[1]/span").click()
# time.sleep(4)
# driver.find_element(By.XPATH, "//*[@id='employee']/div/div[2]/ul[1]/li[1]/div").click()
# time.sleep(3)
# driver.find_element(By.XPATH, "//*[@id='formID2']/div/div[5]/div/div[1]/div/div[1]").click()
# driver.find_element(By.XPATH, "//*[text()='Appointment Status ']/following::div[1]").click()
# driver.find_element(By.XPATH, "//*[text()=' Confirmed ']").click()
# driver.find_element(By.XPATH, "//*[@id='jobDescription']").send_keys("Automation Test")
# driver.find_element(By.XPATH, "//*[@id='schedule_dialog_wrapper']/div[3]/button[2]").click()
# time.sleep(6)

# Add Contact from Contact Tab
# driver.find_element(By.XPATH, "//*[text()='Add New Contact']").click()
# time.sleep(8)
# driver.find_element(By.XPATH, "//*[@placeholder='Role']").send_keys("Tester")
# driver.find_element(By.XPATH, "(//*[@id='First Name'])[2]").send_keys("Peace")
# driver.find_element(By.XPATH, "(//*[@id='Last Name'])[2]").send_keys("Art")
# driver.find_element(By.XPATH, "(//*[text()='Phone'])[4]/following::input[1]").send_keys("234556")
# driver.find_element(By.XPATH, "(//*[@placeholder='Mobile'])[2]").send_keys("784512132")
# driver.find_element(By.XPATH, "(//*[text()='Email'])[2]/following::input[1]").send_keys("automation@gmail.com")
# driver.find_element(By.XPATH, "(//*[text()='Default Contact']/following::input[1])[2]").click()
# driver.find_element(By.XPATH, "(//*[text()='Account Ref'])[2]/following::input[1]").send_keys("Acc44")
# AddressType = driver.find_element(By.XPATH, "//*[@id='custform']/div[1]/div/div[4]/div/div[1]/div/div[2]/app-dynamic-field/select")
# select = Select(AddressType)
# select.select_by_visible_text("Delivery Address")
# driver.find_element(By.XPATH, "//*[@id='contact_zipcodepostcode']").send_keys("MK13")
# driver.find_element(By.XPATH, "//*[@id='contactDynamicform']/span/i").click()
# time.sleep(3)
# driver.find_element(By.XPATH, "//*[text()='Contact Info ']/following::textarea[1]").clear()
# driver.find_element(By.XPATH, "//*[text()='Contact Info ']/following::textarea[1]").send_keys("Temple Tower")
# driver.find_element(By.XPATH, "//*[text()='Contact Info ']/following::textarea[2]").clear()
# driver.find_element(By.XPATH, "//*[text()='Contact Info ']/following::textarea[2]").send_keys("Anna Salai")
# driver.find_element(By.XPATH, "(//*[text()='Town / City']/following::input[1])[2]").clear()
# driver.find_element(By.XPATH, "(//*[text()='Town / City']/following::input[1])[2]").send_keys("Chennai")
# driver.find_element(By.XPATH, "//*[@id='custform']/div[1]/div/div[4]/div/div[5]/div/div[2]/app-dynamic-field/div/input").clear()
# driver.find_element(By.XPATH, "//*[@id='custform']/div[1]/div/div[4]/div/div[5]/div/div[2]/app-dynamic-field/div/input").send_keys("Tamil Nadu")
# driver.find_element(By.XPATH, "(//*[@name='ismarketingemails'])[1]").click()
# pyautogui.scroll(-1500)
# driver.find_element(By.XPATH, "(//*[@name='ismarketingemails'])[1]").click()
# driver.find_element(By.XPATH, "(//*[@name='isdocumentreceived'])[1]").click()
# action = ActionChains(driver)
# action.move_to_element(driver.find_element(By.XPATH, "//*[@id='yes1']/following::i")).click().perform()
# driver.find_element(By.XPATH, "//*[@id='dynamic0']").click()
# driver.find_element(By.XPATH, "//*[@id='dynamic1']").click()
# driver.find_element(By.XPATH, "//*[@id='dynamic2']").click()
# driver.find_element(By.XPATH, "//*[@id='dynamic3']").click()
# driver.find_element(By.XPATH, "//*[@id='dynamic4']").click()
# driver.find_element(By.XPATH, "//*[@id='dynamic5']").click()
# driver.find_element(By.XPATH, "//*[@id='custform']/div[2]/button[1]").click()
# time.sleep(5)

# Delete Contacts
# From Contact Tab
# action = ActionChains(driver)
# action.move_to_element(driver.find_element(By.XPATH, "//*[@id='myGridcontact']/div/div[2]/div[2]/div[3]/div[3]/div/div[1]")).click().perform()
# time.sleep(1)
# driver.find_element(By.XPATH, "//*[@id='deletecomomnotfication']/div/div/div/div/div/button[1]").click()
# time.sleep(5)
# From 3dots
# driver.find_element(By.XPATH, "html/body/app-root/main/section/app-customer/div[1]/ul/li[1]/span").click()
# time.sleep(8)
# driver.find_element(By.XPATH, "//*[@id='cont_contact']/div/div[2]/div[2]/div[3]/div[3]/div[1]/div[1]/div/span/app-contactlisticon/div/div/div/button/i").click()
# driver.find_element(By.XPATH, "//*[@id='cont_contact']/div/div[2]/div[2]/div[3]/div[3]/div[1]/div[1]/div/span/app-contactlisticon/div/div/div/div/button[5]").click()
# time.sleep(1)
# driver.find_element(By.XPATH, "//*[@id='deletecomomnotfication']/div/div/div/div/div/button[1]").click()
# time.sleep(9)